### PR TITLE
Add support for Laravel 6

### PR DESCRIPTION
**Pull request by jkudish**
Adds support for Laravel 6.0+

I saw your notice to make the PR on the project, but as that other project doesn't contain the Laravel specific composer.json file, I am not sure how I would do that. Hope I put this in the right place :)

### CODE REVIEW

**Comment by SubtreeSplit** [comment]
Hey. 
 Thank you for your contribution, but this repository is READ ONLY. You should close this PR and make a new one at http://github.com/php-cache/cache. 

Regards
The bot at SubtreeSplit.com

**Comment by jkudish** [comment]
Hi @prisis can you take a look at this so I don't have to maintain a fork for a version fix?

**Comment by jkudish** [comment]
@prisis appreciate the 👍 but can this get merged? 😬 Thanks!

**Comment by prisis** [comment]
@jkudish need to move this to the php-cache/cache repo

**Comment by jkudish** [comment]
@prisis I saw your notice to make the PR on the php-cache/cache repo, but as that repo doesn't contain the Laravel specific composer.json file, I am not sure how I would do that.

**Comment by prisis** [comment]
@jkudish there is a open pr https://github.com/php-cache/cache/pull/234

I plan to work on the weekend on php-cache

**Comment by jkudish** [comment]
OK -- thanks! FWIW, the only change I needed to make for it to work with my Laravel 6 project was the version bump

**Pull request closed without merging**
